sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lenovo@888
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGQLdHtD1jnhAi5GaBE
    access-key-secret: CoXbZGOYnhbYffIYQaT0djXyWwagli
    bucket-name: sky-take-out-tianshi
