sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lenovo@888
  redis:
    host: localhost
    port: 6379
    password: lenovo@888
    database: 0
  alioss:
    bucket-name: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGQLdHtD1jnhAi5GaBE
    access-key-secret: CoXbZGOYnhbYffIYQaT0djXyWwagli
    endpoint: sky-take-out-tianshi
  wechat:
    appid: wxecf07754e901c1ca
    secret: 9f49add5be1f5d73eca5df566bdac85c
